const express = require('express');
const redis = require('redis');
const bodyParser = require('body-parser');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const http = require('http');
const { Server } = require('socket.io');
const { mongoManager } = require('./mongodb');

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
    cors: {
        origin: ['http://localhost:3001', 'http://127.0.0.1:3001', 'http://165.22.97.51:3001'],
        methods: ['GET', 'POST']
    }
});

// Configuration object
const config = {
    port: process.env.PORT || 3001,
    apiKey: 'supersecretapikey123',
    redis: {
        url: 'redis://:we1we2we3@127.0.0.1:6379',
        retryAttempts: 5,
        retryDelay: 2000
    },
    ttl: {
        autoGenerated: 3600, // 1 hour in seconds
        manualCreated: 2592000, // 30 days in seconds
        configurable: true // Allow admin to change TTL
    }
};

// Simple logger utility
const logger = {
    info: (message) => console.log(`[INFO] ${new Date().toISOString()} - ${message}`),
    error: (message) => console.error(`[ERROR] ${new Date().toISOString()} - ${message}`),
    warn: (message) => console.warn(`[WARN] ${new Date().toISOString()} - ${message}`)
};

// Middleware to validate API key
function validateApiKey(req, res, next) {
    const providedKey = req.query.key || req.body.key || req.headers['x-api-key'];
    
    if (!providedKey) {
        return res.status(401).json({ 
            error: 'API key is required. Please provide it as a query parameter (?key=your_key), in request body, or in x-api-key header.' 
        });
    }
    
    if (providedKey !== config.apiKey) {
        return res.status(401).json({ 
            error: 'Invalid API key. Please check your API key and try again.' 
        });
    }
    
    next();
}

// Redis client setup with retry logic
let redisClient;
let redisConnected = false;
let connectionAttempts = 0;

// Enhanced Redis connection function with retry logic
async function connectRedis() {
    for (let attempt = 1; attempt <= config.redis.retryAttempts; attempt++) {
        try {
            connectionAttempts++;
            logger.info(`Redis connection attempt ${attempt}/${config.redis.retryAttempts}`);

            redisClient = redis.createClient({
                url: config.redis.url
            });

            redisClient.on('error', (err) => {
                logger.error(`Redis Client Error: ${err.message}`);
                redisConnected = false;
            });

            redisClient.on('connect', () => {
                logger.info('✅ Redis Client Connected Successfully');
            });

            redisClient.on('ready', () => {
                logger.info('✅ Redis Client Ready for Operations');
                redisConnected = true;
            });

            redisClient.on('end', () => {
                logger.warn('⚠️ Redis Client Connection Ended');
                redisConnected = false;
            });

            redisClient.on('reconnecting', () => {
                logger.info('🔄 Redis Client Reconnecting...');
            });

            await redisClient.connect(); // <-- এই লাইন মূল ফিক্স
            logger.info('✅ Redis connection established successfully');
            return;

        } catch (error) {
            logger.error(`Redis connection attempt ${attempt} failed: ${error.message}`);
            if (attempt === config.redis.retryAttempts) {
                logger.warn('🔄 All Redis connection attempts failed. Running in standalone mode.');
                redisConnected = false;
                return;
            }
            logger.info(`⏳ Waiting ${config.redis.retryDelay}ms before next attempt...`);
            await new Promise(resolve => setTimeout(resolve, config.redis.retryDelay));
        }
    }
}


// Redis subscriber for real-time email notifications
let redisSubscriber;

// Setup Redis subscriber for external email notifications
async function setupRedisSubscriber() {
    if (!redisConnected) {
        logger.warn('Redis not connected, skipping subscriber setup');
        return;
    }

    try {
        // Create separate Redis client for subscription
        redisSubscriber = redis.createClient({
            url: config.redis.url
        });

        redisSubscriber.on('error', (err) => {
            logger.error(`Redis Subscriber Error: ${err.message}`);
        });

        redisSubscriber.on('connect', () => {
            logger.info('✅ Redis Subscriber Connected');
        });

        await redisSubscriber.connect();

        // Subscribe to new email channel
        await redisSubscriber.subscribe('new_email', (message) => {
            try {
                const emailData = JSON.parse(message);
                logger.info(`📨 New email notification received via Redis: ${emailData.to}`);
                
                // Broadcast to WebSocket clients
                if (emailData.to && emailData.message) {
                    broadcastNewEmail(emailData.to, emailData.message);
                }
            } catch (error) {
                logger.error(`Failed to process Redis email notification: ${error.message}`);
            }
        });

        // Subscribe to email-specific channels (for targeted notifications)
        await redisSubscriber.pSubscribe('channel:email:*', (message, channel) => {
            try {
                const emailData = JSON.parse(message);
                const emailAddress = channel.replace('channel:email:', '');
                logger.info(`📨 Targeted email notification for: ${emailAddress}`);
                
                if (emailData && emailAddress) {
                    broadcastNewEmail(emailAddress, emailData);
                }
            } catch (error) {
                logger.error(`Failed to process targeted email notification: ${error.message}`);
            }
        });

        logger.info('🔔 Redis subscriber setup complete - listening for email notifications');
    } catch (error) {
        logger.error(`Failed to setup Redis subscriber: ${error.message}`);
    }
}

// Initialize Redis connection
connectRedis().then(() => {
    // Setup subscriber after main Redis connection is established
    if (redisConnected) {
        setupRedisSubscriber();
    }
}).catch(error => {
    logger.error(`Failed to initialize Redis: ${error.message}`);
});

// Initialize MongoDB connection
mongoManager.connect().then((connected) => {
    if (connected) {
        logger.info('✅ MongoDB initialized successfully');
        
        // Start periodic cleanup for expired emails
        mongoManager.startPeriodicCleanup(30); // Run every 30 minutes
        logger.info('🔄 TTL-based email expiration system activated');
    } else {
        logger.error('❌ Failed to initialize MongoDB');
    }
}).catch(error => {
    logger.error(`Failed to initialize MongoDB: ${error.message}`);
});

// WebSocket connection handling
io.on('connection', (socket) => {
    logger.info(`Client connected: ${socket.id}`);
    
    // Join email-specific room for targeted notifications
    socket.on('subscribe-email', (email) => {
        if (email && typeof email === 'string') {
            socket.join(`email:${email}`);
            logger.info(`Client ${socket.id} subscribed to email: ${email}`);
            socket.emit('subscribed', { email, message: 'Successfully subscribed to email notifications' });
        }
    });
    
    // Leave email-specific room
    socket.on('unsubscribe-email', (email) => {
        if (email && typeof email === 'string') {
            socket.leave(`email:${email}`);
            logger.info(`Client ${socket.id} unsubscribed from email: ${email}`);
            socket.emit('unsubscribed', { email, message: 'Successfully unsubscribed from email notifications' });
        }
    });
    
    socket.on('disconnect', () => {
        logger.info(`Client disconnected: ${socket.id}`);
    });
});

// Function to broadcast new email notifications
function broadcastNewEmail(email, emailData) {
    // Prepare complete email data for immediate display
    const completeEmailData = {
        id: emailData.id || Date.now().toString(),
        from: emailData.from,
        subject: emailData.subject,
        body: emailData.body,
        timestamp: emailData.timestamp || new Date().toISOString(),
        attachments: emailData.attachments || []
    };
    
    io.to(`email:${email}`).emit('new-email', {
        email,
        message: completeEmailData,
        timestamp: new Date().toISOString(),
        count: 1,
        // ✨ NEW: Full email data for immediate inbox display
        fullEmailData: completeEmailData
    });
    logger.info(`Broadcasted new email notification with full data for: ${email}`);
}

// Input validation middleware
function validateEmail(req, res, next) {
    const email = req.params.email;
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    
    if (!email) {
        return res.status(400).json({ error: 'Email parameter is required' });
    }
    
    if (!emailRegex.test(email)) {
        return res.status(400).json({ error: 'Invalid email format' });
    }
    
    next();
}

// Error handling middleware
function errorHandler(err, req, res, next) {
    logger.error(`Unhandled error: ${err.message}`);
    logger.error(err.stack);
    
    res.status(500).json({
        error: 'Internal server error',
        message: process.env.NODE_ENV === 'development' ? err.message : 'Something went wrong'
    });
}

// Request logging middleware
function requestLogger(req, res, next) {
    const start = Date.now();
    const { method, url, ip } = req;
    
    res.on('finish', () => {
        const duration = Date.now() - start;
        const { statusCode } = res;
        logger.info(`${method} ${url} - ${statusCode} - ${duration}ms - ${ip}`);
    });
    
    next();
}

// Middleware
app.use(cors({
    origin: ['http://localhost:3001', 'http://127.0.0.1:3001'],
    credentials: true
}));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));
app.use(requestLogger);
app.use(express.static('public'));



// Load domains from file
const loadDomains = () => {
  try {
    const data = fs.readFileSync('domains.txt', 'utf8');
    return data.split('\n').filter(domain => domain.trim() !== '');
  } catch (err) {
    return ['oplex.online', 'agrovia.store', 'usashow.live', 'worldwides.help'];
  }
};

// Save domains to file
const saveDomains = (domains) => {
  fs.writeFileSync('domains.txt', domains.join('\n'));
};

// Generate random email
// TTL Management Functions
async function setEmailTTL(email, isManual = false) {
  if (!redisConnected) return;
  
  try {
    const ttlSeconds = isManual ? config.ttl.manualCreated : config.ttl.autoGenerated;
    await redisClient.expire(`inbox:${email}`, ttlSeconds);
    logger.info(`Set TTL for ${email}: ${ttlSeconds} seconds (${isManual ? 'manual' : 'auto-generated'})`);
  } catch (error) {
    logger.error(`Failed to set TTL for ${email}: ${error.message}`);
  }
}

async function updateEmailTTL(email, ttlSeconds) {
  if (!redisConnected) return false;
  
  try {
    await redisClient.expire(`inbox:${email}`, ttlSeconds);
    logger.info(`Updated TTL for ${email}: ${ttlSeconds} seconds`);
    return true;
  } catch (error) {
    logger.error(`Failed to update TTL for ${email}: ${error.message}`);
    return false;
  }
}

app.get('/generate', validateApiKey, async (req, res) => {
  const domains = loadDomains();
  const randomDomain = domains[Math.floor(Math.random() * domains.length)];
  const randomUsername = crypto.randomBytes(8).toString('hex');
  const email = `${randomUsername}@${randomDomain}`;
  
  // Set TTL for auto-generated email (1 hour)
  await setEmailTTL(email, false);
  
  res.json({ 
    email: email,
    type: 'auto-generated',
    ttl: config.ttl.autoGenerated,
    expiresAt: new Date(Date.now() + config.ttl.autoGenerated * 1000).toISOString()
  });
});

// Generate email with specific username and domain
app.get('/generate/manual', validateApiKey, async (req, res) => {
  const { username, domain } = req.query;
  
  if (!username || !domain) {
    return res.status(400).json({ error: 'Username and domain are required' });
  }
  
  const domains = loadDomains();
  if (!domains.includes(domain)) {
    return res.status(400).json({ error: 'Domain not allowed' });
  }
  
  const email = `${username}@${domain}`;
  
  // Set TTL for manually created email (30 days)
  await setEmailTTL(email, true);
  
  res.json({ 
    email: email,
    type: 'manual',
    ttl: config.ttl.manualCreated,
    expiresAt: new Date(Date.now() + config.ttl.manualCreated * 1000).toISOString()
  });
});

// Get all emails for an inbox
app.get('/inbox/:email', validateApiKey, validateEmail, async (req, res) => {
  if (!redisConnected) {
    return res.status(503).json({ 
      error: 'Redis service unavailable', 
      message: 'Email storage is temporarily unavailable. Please try again later.' 
    });
  }
  
  try {
    const email = req.params.email;
    logger.info(`Retrieving inbox for: ${email}`);
    
    const messages = await redisClient.lRange(`inbox:${email}`, 0, -1);
    const parsedMessages = messages.map(msg => {
      try {
        return JSON.parse(msg);
      } catch (parseError) {
        logger.error(`Failed to parse message: ${parseError.message}`);
        return { error: 'Corrupted message data' };
      }
    });
    
    logger.info(`Retrieved ${parsedMessages.length} messages for ${email}`);
    res.json({ 
      email, 
      messages: parsedMessages,
      count: parsedMessages.length,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    logger.error(`Failed to retrieve inbox for ${req.params.email}: ${error.message}`);
    res.status(500).json({ 
      error: 'Failed to retrieve inbox',
      message: 'An error occurred while fetching your emails'
    });
  }
});

// Get specific email by index
app.get('/inbox/:email/:index', validateApiKey, validateEmail, async (req, res) => {
  if (!redisConnected) {
    return res.status(503).json({ 
      error: 'Redis service unavailable',
      message: 'Email storage is temporarily unavailable. Please try again later.'
    });
  }
  
  try {
    const email = req.params.email;
    const index = parseInt(req.params.index);
    
    if (isNaN(index) || index < 0) {
      return res.status(400).json({ 
        error: 'Invalid index',
        message: 'Index must be a non-negative number'
      });
    }
    
    logger.info(`Retrieving message ${index} for: ${email}`);
    
    const message = await redisClient.lIndex(`inbox:${email}`, index);
    if (!message) {
      return res.status(404).json({ 
        error: 'Message not found',
        message: `No message found at index ${index} for ${email}`
      });
    }
    
    let parsedMessage;
    try {
      parsedMessage = JSON.parse(message);
    } catch (parseError) {
      logger.error(`Failed to parse message at index ${index}: ${parseError.message}`);
      return res.status(500).json({ 
        error: 'Corrupted message data',
        message: 'The requested message contains invalid data'
      });
    }
    
    logger.info(`Retrieved message ${index} for ${email}`);
    res.json({ 
      email, 
      index, 
      message: parsedMessage,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    logger.error(`Failed to retrieve message ${req.params.index} for ${req.params.email}: ${error.message}`);
    res.status(500).json({ 
      error: 'Failed to retrieve message',
      message: 'An error occurred while fetching the requested message'
    });
  }
});

// Delete all emails for an inbox
app.delete('/delete/:email', validateApiKey, validateEmail, async (req, res) => {
  if (!redisConnected) {
    return res.status(503).json({ 
      error: 'Redis service unavailable',
      message: 'Email storage is temporarily unavailable. Please try again later.'
    });
  }
  
  try {
    const email = req.params.email;
    logger.info(`Deleting all messages for: ${email}`);
    
    // Check if inbox exists
    const messageCount = await redisClient.lLen(`inbox:${email}`);
    
    if (messageCount === 0) {
      return res.status(404).json({ 
        error: 'Inbox not found',
        message: `No messages found for ${email}`
      });
    }
    
    const deletedCount = await redisClient.del(`inbox:${email}`);
    
    logger.info(`Deleted ${messageCount} messages for ${email}`);
    res.json({ 
      message: `All messages deleted for ${email}`,
      deletedCount: messageCount,
      email,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    logger.error(`Failed to delete messages for ${req.params.email}: ${error.message}`);
    res.status(500).json({ 
      error: 'Failed to delete messages',
      message: 'An error occurred while deleting your emails'
    });
  }
});

// Delete specific email by index
app.delete('/delete/:email/:index', validateApiKey, validateEmail, async (req, res) => {
  if (!redisConnected) {
    return res.status(503).json({ 
      error: 'Redis service unavailable',
      message: 'Email storage is temporarily unavailable. Please try again later.'
    });
  }
  
  try {
    const email = req.params.email;
    const index = parseInt(req.params.index);
    
    if (isNaN(index) || index < 0) {
      return res.status(400).json({ 
        error: 'Invalid index',
        message: 'Index must be a non-negative number'
      });
    }
    
    logger.info(`Deleting message ${index} for: ${email}`);
    
    // Get the message first to check if it exists
    const message = await redisClient.lIndex(`inbox:${email}`, index);
    if (!message) {
      return res.status(404).json({ 
        error: 'Message not found',
        message: `No message found at index ${index} for ${email}`
      });
    }
    
    // Get all messages
    const messages = await redisClient.lRange(`inbox:${email}`, 0, -1);
    
    if (index >= messages.length) {
      return res.status(404).json({ 
        error: 'Index out of range',
        message: `Index ${index} is out of range. Inbox has ${messages.length} messages.`
      });
    }
    
    // Remove the message at the specified index
    const deletedMessage = messages.splice(index, 1)[0];
    
    // Clear the original list and repopulate
    await redisClient.del(`inbox:${email}`);
    if (messages.length > 0) {
      await redisClient.rPush(`inbox:${email}`, messages);
      // Maintain TTL after repopulating
      const ttl = await redisClient.ttl(`inbox:${email}`);
      if (ttl === -1) {
        // If no TTL is set, apply default based on email type
        await setEmailTTL(email, false); // Default to auto-generated TTL
      }
    }
    
    let parsedDeletedMessage;
    try {
      parsedDeletedMessage = JSON.parse(deletedMessage);
    } catch (parseError) {
      parsedDeletedMessage = { error: 'Corrupted message data' };
    }
    
    logger.info(`Deleted message ${index} for ${email}`);
    res.json({ 
      message: `Message at index ${index} deleted for ${email}`,
      deletedMessage: parsedDeletedMessage,
      email,
      index,
      remainingCount: messages.length,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    logger.error(`Failed to delete message ${req.params.index} for ${req.params.email}: ${error.message}`);
    res.status(500).json({ 
      error: 'Failed to delete message',
      message: 'An error occurred while deleting the requested message'
    });
  }
});

// Health check endpoint
app.get('/health', (req, res) => {
  const healthStatus = {
    status: 'OK',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    version: '1.0.0',
    services: {
      redis: {
        connected: redisConnected,
        attempts: connectionAttempts,
        status: redisConnected ? 'Connected' : 'Disconnected'
      },
      api: {
        status: 'Running',
        port: config.port
      }
    },
    memory: {
      used: Math.round(process.memoryUsage().heapUsed / 1024 / 1024) + ' MB',
      total: Math.round(process.memoryUsage().heapTotal / 1024 / 1024) + ' MB'
    }
  };
  
  const statusCode = redisConnected ? 200 : 503;
  res.status(statusCode).json(healthStatus);
});

// Admin API endpoints
app.get('/admin/domains', (req, res) => {
  try {
    const domains = loadDomains();
    logger.info(`Retrieved ${domains.length} domains`);
    res.json({ 
      domains,
      count: domains.length,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    logger.error(`Failed to load domains: ${error.message}`);
    res.status(500).json({ 
      error: 'Failed to load domains',
      message: 'An error occurred while retrieving domain list'
    });
  }
});

app.post('/admin/domains', (req, res) => {
  try {
    const { domain } = req.body;
    
    if (!domain) {
      return res.status(400).json({ 
        error: 'Domain is required',
        message: 'Please provide a domain name'
      });
    }
    
    // Basic domain validation
    const domainRegex = /^[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]?\.[a-zA-Z]{2,}$/;
    if (!domainRegex.test(domain)) {
      return res.status(400).json({ 
        error: 'Invalid domain format',
        message: 'Please provide a valid domain name'
      });
    }
    
    const domains = loadDomains();
    
    if (domains.includes(domain)) {
      return res.status(409).json({ 
        error: 'Domain already exists',
        message: `Domain ${domain} is already in the list`
      });
    }
    
    domains.push(domain);
    saveDomains(domains);
    
    logger.info(`Added new domain: ${domain}`);
    res.status(201).json({ 
      message: 'Domain added successfully', 
      domain,
      domains,
      count: domains.length,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    logger.error(`Failed to add domain: ${error.message}`);
    res.status(500).json({ 
      error: 'Failed to add domain',
      message: 'An error occurred while adding the domain'
    });
  }
});

app.delete('/admin/domains/:domain', (req, res) => {
  try {
    const domainToDelete = req.params.domain;
    let domains = loadDomains();
    
    const initialLength = domains.length;
    domains = domains.filter(domain => domain !== domainToDelete);
    
    if (domains.length === initialLength) {
      return res.status(404).json({ 
        error: 'Domain not found',
        message: `Domain ${domainToDelete} was not found in the list`
      });
    }
    
    saveDomains(domains);
    
    logger.info(`Deleted domain: ${domainToDelete}`);
    res.json({ 
      message: 'Domain deleted successfully', 
      deletedDomain: domainToDelete,
      domains,
      count: domains.length,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    logger.error(`Failed to delete domain: ${error.message}`);
    res.status(500).json({ 
      error: 'Failed to delete domain',
      message: 'An error occurred while deleting the domain'
    });
  }
});

// Email receiving webhook endpoint
app.post('/webhook/receive', validateApiKey, async (req, res) => {
  try {
    const { to, from, subject, text, html, timestamp } = req.body;
    
    if (!to) {
      return res.status(400).json({
        error: 'Missing recipient email',
        message: 'The "to" field is required'
      });
    }
    
    // Create email message object
    const emailMessage = {
      from: from || 'unknown@sender.com',
      subject: subject || 'No Subject',
      text: text || '',
      html: html || '',
      timestamp: timestamp || new Date().toISOString(),
      id: crypto.randomBytes(16).toString('hex')
    };
    
    if (redisConnected) {
      // Store the email in Redis
      await redisClient.rPush(`inbox:${to}`, JSON.stringify(emailMessage));
      
      // Check if TTL exists, if not set default TTL
      const currentTTL = await redisClient.ttl(`inbox:${to}`);
      if (currentTTL === -1) {
        // No TTL set, apply default auto-generated TTL
        await setEmailTTL(to, false);
      }
      
      // Broadcast real-time notification
      broadcastNewEmail(to, emailMessage);
      
      logger.info(`Email received and stored for ${to} from ${emailMessage.from}`);
      
      res.json({
        message: 'Email received and stored successfully',
        recipient: to,
        messageId: emailMessage.id,
        timestamp: emailMessage.timestamp,
        realTimeNotified: true
      });
    } else {
      logger.warn(`Email received for ${to} but Redis not connected - email lost`);
      res.status(503).json({
        error: 'Redis not connected',
        message: 'Cannot store email - Redis service unavailable'
      });
    }
  } catch (error) {
    logger.error(`Failed to receive email: ${error.message}`);
    res.status(500).json({
      error: 'Failed to process incoming email',
      message: error.message
    });
  }
});

// Admin TTL Management Endpoints
app.get('/admin/ttl/config', (req, res) => {
  res.json({
    ttl: config.ttl,
    timestamp: new Date().toISOString()
  });
});

// Admin dashboard statistics endpoint
app.get('/admin/stats', async (req, res) => {
  try {
    if (!redisClient || !redisConnected) {
      return res.json({
        success: true,
        stats: {
          totalInboxes: 0,
          activeInboxes: 0,
          emailsStored: 0,
          redisConnected: false,
          redisMemory: 'N/A',
          redisPerformance: 'N/A'
        }
      });
    }

    // Get all inbox keys
    const inboxKeys = await redisClient.keys('inbox:*');
    const totalInboxes = inboxKeys.length;
    
    // Count active inboxes (with TTL > 0)
    let activeInboxes = 0;
    let totalEmails = 0;
    
    for (const key of inboxKeys) {
      const ttl = await redisClient.ttl(key);
      if (ttl > 0 || ttl === -1) { // -1 means no expiration
        activeInboxes++;
      }
      
      // Count emails in this inbox
      const emailCount = await redisClient.lLen(key);
      totalEmails += emailCount;
    }
    
    // Get Redis memory info
    const redisInfo = await redisClient.info('memory');
    const memoryLines = redisInfo.split('\r\n');
    const usedMemory = memoryLines.find(line => line.startsWith('used_memory_human:'))?.split(':')[1] || 'N/A';
    
    // Performance test - measure Redis response time
    const startTime = Date.now();
    await redisClient.ping();
    const responseTime = Date.now() - startTime;
    
    // Get Redis server info
    const serverInfo = await redisClient.info('server');
    const serverLines = serverInfo.split('\r\n');
    const redisVersion = serverLines.find(line => line.startsWith('redis_version:'))?.split(':')[1] || 'Unknown';
    
    res.json({
      success: true,
      stats: {
        totalInboxes,
        activeInboxes,
        emailsStored: totalEmails,
        redisConnected: true,
        redisMemory: usedMemory,
        redisPerformance: {
          responseTime: `${responseTime}ms`,
          version: redisVersion,
          status: responseTime < 10 ? 'Excellent' : responseTime < 50 ? 'Good' : 'Slow'
        }
      }
    });
  } catch (error) {
    logger.error(`Error getting admin stats: ${error.message}`);
    res.status(500).json({ success: false, error: 'Failed to get statistics' });
  }
});

app.post('/admin/ttl/config', (req, res) => {
  try {
    const { autoGenerated, manualCreated } = req.body;
    
    if (autoGenerated && typeof autoGenerated === 'number' && autoGenerated > 0) {
      config.ttl.autoGenerated = autoGenerated;
    }
    
    if (manualCreated && typeof manualCreated === 'number' && manualCreated > 0) {
      config.ttl.manualCreated = manualCreated;
    }
    
    logger.info(`TTL configuration updated: auto=${config.ttl.autoGenerated}s, manual=${config.ttl.manualCreated}s`);
    
    res.json({
      message: 'TTL configuration updated successfully',
      ttl: config.ttl,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    logger.error(`Failed to update TTL configuration: ${error.message}`);
    res.status(500).json({
      error: 'Failed to update TTL configuration',
      message: error.message
    });
  }
});

app.post('/admin/ttl/email', async (req, res) => {
  try {
    const { email, ttlSeconds } = req.body;
    
    if (!email || typeof ttlSeconds !== 'number' || ttlSeconds < 0) {
      return res.status(400).json({
        error: 'Invalid parameters',
        message: 'Email and valid TTL seconds are required'
      });
    }
    
    const success = await updateEmailTTL(email, ttlSeconds);
    
    if (success) {
      res.json({
        message: 'Email TTL updated successfully',
        email,
        ttlSeconds,
        expiresAt: ttlSeconds > 0 ? new Date(Date.now() + ttlSeconds * 1000).toISOString() : null,
        timestamp: new Date().toISOString()
      });
    } else {
      res.status(500).json({
        error: 'Failed to update email TTL',
        message: 'Redis operation failed'
      });
    }
  } catch (error) {
    logger.error(`Failed to update email TTL: ${error.message}`);
    res.status(500).json({
      error: 'Failed to update email TTL',
      message: error.message
    });
  }
});

app.delete('/admin/ttl/email/:email', async (req, res) => {
  try {
    const { email } = req.params;
    
    if (!redisConnected) {
      return res.status(503).json({
        error: 'Redis not connected',
        message: 'Cannot delete email - Redis service unavailable'
      });
    }
    
    const deleted = await redisClient.del(`inbox:${email}`);
    
    if (deleted > 0) {
      logger.info(`Permanently deleted email inbox: ${email}`);
      res.json({
        message: 'Email inbox deleted permanently',
        email,
        timestamp: new Date().toISOString()
      });
    } else {
      res.status(404).json({
        error: 'Email not found',
        message: 'No inbox found for the specified email'
      });
    }
  } catch (error) {
    logger.error(`Failed to delete email inbox: ${error.message}`);
    res.status(500).json({
      error: 'Failed to delete email inbox',
      message: error.message
    });
  }
});

// MongoDB API Routes
// MongoDB Health Check
app.get('/api/mongodb/health', validateApiKey, async (req, res) => {
  try {
    const health = await mongoManager.healthCheck();
    res.json(health);
  } catch (error) {
    logger.error(`MongoDB health check failed: ${error.message}`);
    res.status(500).json({
      error: 'Health check failed',
      message: error.message
    });
  }
});

// MongoDB Connection Test
app.post('/api/mongodb/test', validateApiKey, async (req, res) => {
  try {
    const health = await mongoManager.healthCheck();
    if (health.status === 'healthy') {
      res.json({ message: 'MongoDB connection test successful', status: health.status });
    } else {
      res.status(500).json({ error: 'MongoDB connection test failed', status: health.status });
    }
  } catch (error) {
    logger.error(`MongoDB connection test failed: ${error.message}`);
    res.status(500).json({
      error: 'Connection test failed',
      message: error.message
    });
  }
});

// Get Emails from MongoDB
app.get('/api/mongodb/emails', validateApiKey, async (req, res) => {
  try {
    const { limit = 50, skip = 0 } = req.query;
    const emails = await mongoManager.getEmails({}, parseInt(limit), parseInt(skip));
    res.json({ emails, count: emails.length });
  } catch (error) {
    logger.error(`Failed to fetch emails from MongoDB: ${error.message}`);
    res.status(500).json({
      error: 'Failed to fetch emails',
      message: error.message
    });
  }
});

// Search Emails in MongoDB
app.get('/api/mongodb/emails/search', validateApiKey, async (req, res) => {
  try {
    const { q } = req.query;
    if (!q) {
      return res.status(400).json({ error: 'Search query is required' });
    }
    
    const filter = {
      $or: [
        { to: { $regex: q, $options: 'i' } },
        { from: { $regex: q, $options: 'i' } },
        { subject: { $regex: q, $options: 'i' } },
        { content: { $regex: q, $options: 'i' } }
      ]
    };
    
    const emails = await mongoManager.getEmails(filter, 50, 0);
    res.json({ emails, count: emails.length, query: q });
  } catch (error) {
    logger.error(`Failed to search emails in MongoDB: ${error.message}`);
    res.status(500).json({
      error: 'Failed to search emails',
      message: error.message
    });
  }
});

// Delete Email from MongoDB
app.delete('/api/mongodb/emails/:id', validateApiKey, async (req, res) => {
  try {
    const { id } = req.params;
    const { ObjectId } = require('mongodb');
    
    const result = await mongoManager.deleteEmail(new ObjectId(id));
    if (result.deletedCount > 0) {
      res.json({ message: 'Email deleted successfully', deletedCount: result.deletedCount });
    } else {
      res.status(404).json({ error: 'Email not found' });
    }
  } catch (error) {
    logger.error(`Failed to delete email from MongoDB: ${error.message}`);
    res.status(500).json({
      error: 'Failed to delete email',
      message: error.message
    });
  }
});

// Get Analytics from MongoDB
app.get('/api/mongodb/analytics', validateApiKey, async (req, res) => {
  try {
    const { type = 'all', limit = 100 } = req.query;
    const filter = type !== 'all' ? { type } : {};
    
    const analytics = await mongoManager.getAnalytics(filter, parseInt(limit));
    res.json({ analytics, count: analytics.length, type });
  } catch (error) {
    logger.error(`Failed to fetch analytics from MongoDB: ${error.message}`);
    res.status(500).json({
      error: 'Failed to fetch analytics',
      message: error.message
    });
  }
});

// Add Domain to MongoDB
app.post('/api/mongodb/domains', validateApiKey, async (req, res) => {
  try {
    const { domain } = req.body;
    if (!domain) {
      return res.status(400).json({ error: 'Domain is required' });
    }
    
    const result = await mongoManager.saveDomain({ domain, status: 'active' });
    res.json({ message: 'Domain added successfully', domain, id: result.insertedId });
  } catch (error) {
    logger.error(`Failed to add domain to MongoDB: ${error.message}`);
    res.status(500).json({
      error: 'Failed to add domain',
      message: error.message
    });
  }
});

// Get Domains from MongoDB
app.get('/api/mongodb/domains', validateApiKey, async (req, res) => {
  try {
    const domains = await mongoManager.getDomains();
    res.json({ domains, count: domains.length });
  } catch (error) {
    logger.error(`Failed to fetch domains from MongoDB: ${error.message}`);
    res.status(500).json({
      error: 'Failed to fetch domains',
      message: error.message
    });
  }
});

// Store Generated Email for User
app.post('/api/mongodb/emails/store', validateApiKey, async (req, res) => {
  try {
    const { email, type, ttl, expiresAt, deviceId, isActive = true } = req.body;
    
    if (!email || !deviceId) {
      return res.status(400).json({ error: 'Email and deviceId are required' });
    }
    
    const emailData = {
      email,
      type: type || 'random',
      ttl: ttl || 3600,
      expiresAt: expiresAt || new Date(Date.now() + (ttl || 3600) * 1000),
      deviceId,
      isActive,
      createdAt: new Date(),
      id: require('crypto').randomUUID()
    };
    
    const result = await mongoManager.saveGeneratedEmail(emailData);
    res.status(201).json({ 
      message: 'Email stored successfully', 
      email: emailData, 
      id: result.insertedId 
    });
  } catch (error) {
    logger.error(`Failed to store generated email: ${error.message}`);
    
    if (error.message === 'MongoDB not connected') {
      res.status(503).json({
        error: 'Database temporarily unavailable',
        message: 'MongoDB connection is not established. Please try again later.',
        fallback: 'Email generation is working, but storage is temporarily disabled.'
      });
    } else {
      res.status(500).json({
        error: 'Failed to store email',
        message: error.message
      });
    }
  }
});

// Get User's Generated Emails
app.get('/api/mongodb/emails/user/:deviceId', validateApiKey, async (req, res) => {
  try {
    const { deviceId } = req.params;
    const { limit = 50, skip = 0, activeOnly = 'false' } = req.query;
    
    if (!deviceId) {
      return res.status(400).json({ error: 'Device ID is required' });
    }
    
    const filter = { deviceId };
    if (activeOnly === 'true') {
      filter.isActive = true;
    }
    
    const emails = await mongoManager.getUserGeneratedEmails(filter, parseInt(limit), parseInt(skip));
    res.json({ 
      emails, 
      count: emails.length, 
      deviceId,
      activeOnly: activeOnly === 'true'
    });
  } catch (error) {
    logger.error(`Failed to fetch user emails: ${error.message}`);
    
    if (error.message === 'MongoDB not connected') {
      res.status(503).json({
        error: 'Database temporarily unavailable',
        message: 'MongoDB connection is not established. Email history is not available.',
        fallback: 'Please check MongoDB Atlas configuration and IP whitelist.',
        emails: [],
        count: 0
      });
    } else {
      res.status(500).json({
        error: 'Failed to fetch user emails',
        message: error.message
      });
    }
  }
});

// Update Email Status
app.put('/api/mongodb/emails/:id/status', validateApiKey, async (req, res) => {
  try {
    const { id } = req.params;
    const { isActive } = req.body;
    
    if (typeof isActive !== 'boolean') {
      return res.status(400).json({ error: 'isActive must be a boolean' });
    }
    
    const { ObjectId } = require('mongodb');
    const result = await mongoManager.updateGeneratedEmailStatus(new ObjectId(id), isActive);
    
    if (result.modifiedCount > 0) {
      res.json({ 
        message: 'Email status updated successfully', 
        modifiedCount: result.modifiedCount,
        isActive 
      });
    } else {
      res.status(404).json({ error: 'Email not found or no changes made' });
    }
  } catch (error) {
    logger.error(`Failed to update email status: ${error.message}`);
    res.status(500).json({
      error: 'Failed to update email status',
      message: error.message
    });
  }
});

// Delete Generated Email
app.delete('/api/mongodb/emails/:id', validateApiKey, async (req, res) => {
  try {
    const { id } = req.params;
    const { ObjectId } = require('mongodb');
    
    const result = await mongoManager.deleteGeneratedEmail(new ObjectId(id));
    if (result.deletedCount > 0) {
      res.json({ message: 'Generated email deleted successfully', deletedCount: result.deletedCount });
    } else {
      res.status(404).json({ error: 'Generated email not found' });
    }
  } catch (error) {
    logger.error(`Failed to delete generated email: ${error.message}`);
    res.status(500).json({
      error: 'Failed to delete generated email',
      message: error.message
    });
  }
});

// MongoDB TTL Management Endpoints

// Extend Email TTL
app.put('/api/mongodb/emails/:id/extend-ttl', validateApiKey, async (req, res) => {
  try {
    const { id } = req.params;
    const { additionalSeconds = 3600 } = req.body;
    
    if (typeof additionalSeconds !== 'number' || additionalSeconds <= 0) {
      return res.status(400).json({ error: 'additionalSeconds must be a positive number' });
    }
    
    const { ObjectId } = require('mongodb');
    const result = await mongoManager.extendEmailTTL(new ObjectId(id), additionalSeconds);
    
    if (result.modifiedCount > 0) {
      res.json({ 
        message: 'Email TTL extended successfully', 
        modifiedCount: result.modifiedCount,
        additionalSeconds,
        newExpiresAt: new Date(Date.now() + additionalSeconds * 1000).toISOString()
      });
    } else {
      res.status(404).json({ error: 'Email not found' });
    }
  } catch (error) {
    logger.error(`Failed to extend email TTL: ${error.message}`);
    
    if (error.message === 'MongoDB not connected') {
      res.status(503).json({
        error: 'Database temporarily unavailable',
        message: 'MongoDB connection is not established. Please try again later.'
      });
    } else {
      res.status(500).json({
        error: 'Failed to extend email TTL',
        message: error.message
      });
    }
  }
});

// Manual Cleanup of Expired Emails
app.post('/api/mongodb/emails/cleanup', validateApiKey, async (req, res) => {
  try {
    const { action = 'deactivate' } = req.body; // 'deactivate' or 'delete'
    
    let result;
    if (action === 'delete') {
      result = await mongoManager.cleanupExpiredEmails();
      res.json({ 
        message: 'Expired emails deleted successfully', 
        deletedCount: result.deletedCount,
        action: 'deleted'
      });
    } else {
      result = await mongoManager.deactivateExpiredEmails();
      res.json({ 
        message: 'Expired emails deactivated successfully', 
        modifiedCount: result.modifiedCount,
        action: 'deactivated'
      });
    }
  } catch (error) {
    logger.error(`Failed to cleanup expired emails: ${error.message}`);
    
    if (error.message === 'MongoDB not connected') {
      res.status(503).json({
        error: 'Database temporarily unavailable',
        message: 'MongoDB connection is not established. Please try again later.'
      });
    } else {
      res.status(500).json({
        error: 'Failed to cleanup expired emails',
        message: error.message
      });
    }
  }
});

// Get Email Expiration Status
app.get('/api/mongodb/emails/:id/expiration', validateApiKey, async (req, res) => {
  try {
    const { id } = req.params;
    const { ObjectId } = require('mongodb');
    
    const collection = mongoManager.getCollection('generated_emails');
    const email = await collection.findOne({ _id: new ObjectId(id) });
    
    if (!email) {
      return res.status(404).json({ error: 'Email not found' });
    }
    
    const now = new Date();
    const isExpired = email.expiresAt && new Date(email.expiresAt) < now;
    const timeUntilExpiry = email.expiresAt ? new Date(email.expiresAt).getTime() - now.getTime() : null;
    
    res.json({
      emailId: id,
      email: email.email,
      isActive: email.isActive,
      isExpired,
      expiresAt: email.expiresAt,
      ttl: email.ttl,
      timeUntilExpiryMs: timeUntilExpiry > 0 ? timeUntilExpiry : 0,
      timeUntilExpiryHuman: timeUntilExpiry > 0 ? `${Math.floor(timeUntilExpiry / 1000 / 60)} minutes` : 'Expired',
      createdAt: email.createdAt,
      updatedAt: email.updatedAt
    });
  } catch (error) {
    logger.error(`Failed to get email expiration status: ${error.message}`);
    
    if (error.message === 'MongoDB not connected') {
      res.status(503).json({
        error: 'Database temporarily unavailable',
        message: 'MongoDB connection is not established. Please try again later.'
      });
    } else {
      res.status(500).json({
        error: 'Failed to get email expiration status',
        message: error.message
      });
    }
  }
});

// Serve MongoDB management page
app.get('/mongodb', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'mongodb.html'));
});

// Serve admin panel
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// 404 handler for undefined routes
app.use('*', (req, res) => {
  logger.warn(`404 - Route not found: ${req.method} ${req.originalUrl}`);
  res.status(404).json({
    error: 'Route not found',
    message: `The requested endpoint ${req.method} ${req.originalUrl} does not exist`,
    availableEndpoints: {
      api: [
        'GET /generate',
        'GET /generate/manual',
        'GET /inbox/:email',
        'GET /inbox/:email/:index',
        'DELETE /delete/:email',
        'DELETE /delete/:email/:index'
      ],
      admin: [
        'GET /admin/domains',
        'POST /admin/domains',
        'DELETE /admin/domains/:domain'
      ],
      system: [
        'GET /health',
        'GET /'
      ]
    },
    timestamp: new Date().toISOString()
  });
});

// Global error handling middleware (must be last)
app.use(errorHandler);

// Graceful shutdown handling
process.on('SIGTERM', async () => {
  logger.info('🛑 SIGTERM received, shutting down gracefully...');
  
  // Close Redis subscriber
  if (redisSubscriber) {
    try {
      await redisSubscriber.quit();
      logger.info('✅ Redis subscriber connection closed');
    } catch (error) {
      logger.error(`Error closing Redis subscriber: ${error.message}`);
    }
  }
  
  // Close main Redis client
  if (redisClient && redisConnected) {
    try {
      await redisClient.quit();
      logger.info('✅ Redis connection closed');
    } catch (error) {
      logger.error(`Error closing Redis connection: ${error.message}`);
    }
  }
  
  process.exit(0);
});

process.on('SIGINT', async () => {
  logger.info('🛑 SIGINT received, shutting down gracefully...');
  
  // Close Redis subscriber
  if (redisSubscriber) {
    try {
      await redisSubscriber.quit();
      logger.info('✅ Redis subscriber connection closed');
    } catch (error) {
      logger.error(`Error closing Redis subscriber: ${error.message}`);
    }
  }
  
  // Close main Redis client
  if (redisClient && redisConnected) {
    try {
      await redisClient.quit();
      logger.info('✅ Redis connection closed');
    } catch (error) {
      logger.error(`Error closing Redis connection: ${error.message}`);
    }
  }
  
  process.exit(0);
});

// Start the server
server.listen(config.port, () => {
  logger.info(`🚀 TurboMail API Server started successfully`);
  logger.info(`📡 Server running on port ${config.port}`);
  logger.info(`🌐 Admin Panel: http://localhost:${config.port}`);
  logger.info(`🔗 API Base URL: http://localhost:${config.port}`);
  logger.info(`❤️  Health Check: http://localhost:${config.port}/health`);
  logger.info(`🔑 API Key: ${config.apiKey}`);
  logger.info(`📊 Memory Usage: ${Math.round(process.memoryUsage().heapUsed / 1024 / 1024)} MB`);
  logger.info(`🔌 WebSocket Server: Ready for real-time notifications`);
  
  if (!redisConnected) {
    logger.warn(`⚠️  Redis not connected - running in standalone mode`);
    logger.warn(`📧 Email persistence disabled until Redis is available`);
  }
  
  logger.info(`✨ TurboMail is ready to handle requests!`);
});

module.exports = app;