name: turbomail
description: "TurboMail - Temporary Email Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.5

  # Socket.IO for real-time updates
  socket_io_client: ^3.1.2
  
  # Permission handling
  permission_handler: ^11.3.1
  dio: ^5.8.0+1
  
  # Device ID and storage
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  
  # QR Code generation
  qr_flutter: ^4.1.0
  rive: ^0.13.20
  
  # Lottie animations
  lottie: ^3.1.2
  in_app_purchase: ^3.2.3
  
  # HTML rendering
  webview_flutter: ^4.4.2
  flutter_html: ^3.0.0-beta.2
  
  # Google Mobile Ads
  google_mobile_ads: ^5.1.0
  
  # App updates
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.1
  
  # HTTP requests
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
